# Generated by Django 4.1.6 on 2023-02-14 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_rename_tarea_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tarea',
        ),
    ]
