# Generated by Django 4.1.6 on 2023-02-15 02:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_tarea_delete_modelotarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Task',
        ),
    ]
