# Generated by Django 4.1.6 on 2023-02-15 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_tarea_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
