# Generated by Django 4.1.6 on 2023-02-15 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='reated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
