# Generated by Django 4.1.6 on 2023-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_created_task_reated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reated',
            new_name='created',
        ),
    ]
